"""empty message

Revision ID: 865ac344ba2e
Revises: 
Create Date: 2020-03-31 05:59:39.785216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865ac344ba2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Authorization')
    # ### end Alembic commands ###
